// DO NOT EDIT — this file is auto-generated.
// Generated by scripts/generate_ts_types.py from SCHEMA_VERSION 1.0

export const SCHEMA_VERSION = "1.0";

export interface SimulationConfig {
  n_agents: number;
  grid_size: number;
  seed: number;
  protocol_name: string;
  protocol_params?: Record<string, unknown>;
  perception_radius?: number;
  discount_factor?: number;
  movement_budget?: number;
  matching_protocol_name?: string;
  info_env_name?: string;
  info_env_params?: Record<string, unknown>;
  schema_version?: string;
  run_id?: string;
  manifest_id?: string | null;
  treatment_arm?: string | null;
}

export interface AgentSnapshot {
  agent_id: string;
  position: [number, number];
  endowment: [number, number];
  alpha: number;
  utility: number;
  has_beliefs?: boolean;
  n_trades_in_memory?: number;
  n_type_beliefs?: number;
}

export interface TargetEvaluation {
  target_id: string;
  target_position: [number, number];
  distance: number;
  ticks_to_reach: number;
  expected_surplus: number;
  discounted_value: number;
  observed_alpha: number;
  used_belief?: boolean;
  believed_alpha?: number | null;
}

export interface SearchDecision {
  agent_id: string;
  position: [number, number];
  visible_agents: number;
  evaluations: TargetEvaluation[];
  chosen_target_id: string | null;
  chosen_value: number;
}

export interface MovementEvent {
  agent_id: string;
  from_pos: [number, number];
  to_pos: [number, number];
  target_id: string | null;
  reason: string;
}

export interface TradeEvent {
  agent1_id: string;
  agent2_id: string;
  proposer_id: string;
  pre_holdings: [[number, number], [number, number]];
  post_allocations: [[number, number], [number, number]];
  utilities: [number, number];
  gains: [number, number];
  trade_occurred: boolean;
}

export interface CommitmentFormedEvent {
  agent_a: string;
  agent_b: string;
}

export interface CommitmentBrokenEvent {
  agent_a: string;
  agent_b: string;
  reason: string;
}

export interface TypeBeliefSnapshot {
  target_agent_id: string;
  believed_alpha: number;
  confidence: number;
  n_interactions: number;
}

export interface PriceBeliefSnapshot {
  mean: number;
  variance: number;
  n_observations: number;
}

export interface BeliefSnapshot {
  agent_id: string;
  type_beliefs: TypeBeliefSnapshot[];
  price_belief: PriceBeliefSnapshot;
  n_trades_in_memory: number;
}

export interface TickRecord {
  tick: number;
  agent_snapshots: AgentSnapshot[];
  search_decisions: SearchDecision[];
  movements: MovementEvent[];
  trades: TradeEvent[];
  total_welfare: number;
  cumulative_trades: number;
  commitments_formed?: CommitmentFormedEvent[];
  commitments_broken?: CommitmentBrokenEvent[];
  belief_snapshots?: BeliefSnapshot[];
}

export interface RunSummary {
  total_ticks: number;
  final_welfare: number;
  total_trades: number;
  welfare_gain: number;
}
