"""
Agent representation with separation of private state and observable type.

This module implements the core abstraction where agents have:
1. Private state: True characteristics (preferences, endowments)
2. Observable type: What other agents can perceive

This separation is architecturally critical for future information environments:
- Full information: type = private state (MVP default)
- Private information: type may be hidden or partially revealed
- Signaling: agents take costly actions to reveal type

Reference: CLAUDE.md, O&R-G Ch 11, Kreps II Ch 20-21
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
import uuid

from microecon.bundle import Bundle
from microecon.preferences import CobbDouglas


@dataclass
class AgentPrivateState:
    """
    An agent's true private characteristics.

    These are the agent's actual preferences and holdings, which determine
    real behavior and payoffs. In complete information settings, these are
    observable; in incomplete information, they may be hidden.

    Attributes:
        preferences: The agent's utility function (Cobb-Douglas for MVP)
        endowment: The agent's current holdings of both goods
    """
    preferences: CobbDouglas
    endowment: Bundle

    def utility(self) -> float:
        """Compute utility from current endowment."""
        return self.preferences.utility(self.endowment)

    def utility_of(self, bundle: Bundle) -> float:
        """Compute utility of an arbitrary bundle."""
        return self.preferences.utility(bundle)


@dataclass(frozen=True)
class AgentType:
    """
    An agent's publicly observable characteristics.

    In game-theoretic terms, a "type" is the information available to other
    players for conditioning their strategies. The content of type depends
    on the information environment.

    For the MVP (full information), type = private state.
    Future extensions may have type reveal only partial information.

    Attributes:
        preferences: Observable preference parameter (alpha for Cobb-Douglas)
        endowment: Observable holdings
    """
    preferences: CobbDouglas
    endowment: Bundle

    @staticmethod
    def from_private_state(state: AgentPrivateState) -> AgentType:
        """Create observable type from private state (full information case)."""
        return AgentType(
            preferences=state.preferences,
            endowment=state.endowment,
        )


@dataclass
class Agent:
    """
    An economic agent in the simulation.

    Agents have:
    - A unique identifier
    - Private state (true preferences and endowments)
    - Search parameters (perception radius, discount factor)
    - Movement budget per tick

    The observable type is generated by the information environment,
    not stored directly on the agent.

    Attributes:
        id: Unique identifier
        private_state: True characteristics
        perception_radius: How far the agent can see (in grid units)
        discount_factor: Time preference (delta), used to discount future trades
        movement_budget: Squares per tick the agent can move
    """
    private_state: AgentPrivateState
    perception_radius: float = 3.0
    discount_factor: float = 0.95
    movement_budget: int = 1
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])

    @property
    def preferences(self) -> CobbDouglas:
        """Convenience accessor for preferences."""
        return self.private_state.preferences

    @property
    def endowment(self) -> Bundle:
        """Convenience accessor for current endowment."""
        return self.private_state.endowment

    @endowment.setter
    def endowment(self, value: Bundle) -> None:
        """Update the agent's endowment (e.g., after trade)."""
        self.private_state.endowment = value

    def utility(self) -> float:
        """Compute current utility level."""
        return self.private_state.utility()

    def utility_of(self, bundle: Bundle) -> float:
        """Compute utility of an arbitrary bundle."""
        return self.private_state.utility_of(bundle)

    def would_gain_from(self, new_bundle: Bundle) -> bool:
        """Check if trading to new_bundle would increase utility."""
        return self.utility_of(new_bundle) > self.utility()

    def __hash__(self) -> int:
        return hash(self.id)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Agent):
            return NotImplemented
        return self.id == other.id


def create_agent(
    alpha: float,
    endowment_x: float,
    endowment_y: float,
    perception_radius: float = 3.0,
    discount_factor: float = 0.95,
    movement_budget: int = 1,
) -> Agent:
    """
    Factory function to create an agent with Cobb-Douglas preferences.

    Args:
        alpha: Cobb-Douglas preference parameter in (0, 1)
        endowment_x: Initial holdings of good x
        endowment_y: Initial holdings of good y
        perception_radius: How far the agent can observe
        discount_factor: Time preference delta in (0, 1)
        movement_budget: Squares per tick

    Returns:
        A new Agent instance
    """
    preferences = CobbDouglas(alpha)
    endowment = Bundle(endowment_x, endowment_y)
    private_state = AgentPrivateState(preferences, endowment)

    return Agent(
        private_state=private_state,
        perception_radius=perception_radius,
        discount_factor=discount_factor,
        movement_budget=movement_budget,
    )
