"""
Agent representation with separation of private state and observable type.

This module implements the core abstraction where agents have:
1. Private state: True characteristics (preferences, endowments)
2. Observable type: What other agents can perceive
3. Memory and beliefs: Observation history and learned beliefs (optional)

This separation is architecturally critical for future information environments:
- Full information: type = private state (MVP default)
- Private information: type may be hidden or partially revealed
- Signaling: agents take costly actions to reveal type

Reference: CLAUDE.md, O&R-G Ch 11, Kreps II Ch 20-21
See also: ADR-BELIEF-ARCHITECTURE.md for belief system design
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import TYPE_CHECKING
import uuid

from microecon.bundle import Bundle
from microecon.preferences import CobbDouglas

if TYPE_CHECKING:
    from microecon.beliefs import (
        AgentMemory,
        PriceBelief,
        TypeBelief,
        BeliefUpdateRule,
    )


@dataclass
class AgentPrivateState:
    """
    An agent's true private characteristics.

    These are the agent's actual preferences and holdings, which determine
    real behavior and payoffs. In complete information settings, these are
    observable; in incomplete information, they may be hidden.

    Attributes:
        preferences: The agent's utility function (Cobb-Douglas for MVP)
        endowment: The agent's current holdings of both goods
    """
    preferences: CobbDouglas
    endowment: Bundle

    def utility(self) -> float:
        """Compute utility from current endowment."""
        return self.preferences.utility(self.endowment)

    def utility_of(self, bundle: Bundle) -> float:
        """Compute utility of an arbitrary bundle."""
        return self.preferences.utility(bundle)


@dataclass(frozen=True)
class AgentType:
    """
    An agent's publicly observable characteristics.

    In game-theoretic terms, a "type" is the information available to other
    players for conditioning their strategies. The content of type depends
    on the information environment.

    For the MVP (full information), type = private state.
    Future extensions may have type reveal only partial information.

    Attributes:
        preferences: Observable preference parameter (alpha for Cobb-Douglas)
        endowment: Observable holdings
    """
    preferences: CobbDouglas
    endowment: Bundle

    @staticmethod
    def from_private_state(state: AgentPrivateState) -> AgentType:
        """Create observable type from private state (full information case)."""
        return AgentType(
            preferences=state.preferences,
            endowment=state.endowment,
        )


@dataclass
class Agent:
    """
    An economic agent in the simulation.

    Agents have:
    - A unique identifier
    - Private state (true preferences and endowments)
    - Search parameters (perception radius, discount factor)
    - Movement budget per tick
    - Optional: Memory and beliefs for learning (see ADR-BELIEF-ARCHITECTURE.md)

    The observable type is generated by the information environment,
    not stored directly on the agent.

    Attributes:
        id: Unique identifier
        private_state: True characteristics
        perception_radius: How far the agent can see (in grid units)
        discount_factor: Time preference (delta), used to discount future trades
        bargaining_power: Intrinsic institutional bargaining power (w_i), used by
            AsymmetricNashBargainingProtocol. Independent of discount_factor.
        movement_budget: Squares per tick the agent can move
        memory: Observation and interaction history (optional)
        price_belief: Belief about exchange rates (optional)
        type_beliefs: Beliefs about other agents' types (optional)
        update_rule: Rule for updating beliefs (optional)
    """
    private_state: AgentPrivateState
    perception_radius: float = 3.0
    discount_factor: float = 0.95
    bargaining_power: float = 1.0
    movement_budget: int = 1
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])

    # Belief system (optional, for backward compatibility)
    # These are initialized to None by default; use enable_beliefs() to activate
    memory: AgentMemory | None = field(default=None, repr=False)
    price_belief: PriceBelief | None = field(default=None, repr=False)
    type_beliefs: dict[str, TypeBelief] | None = field(default=None, repr=False)
    update_rule: BeliefUpdateRule | None = field(default=None, repr=False)

    @property
    def preferences(self) -> CobbDouglas:
        """Convenience accessor for preferences."""
        return self.private_state.preferences

    @property
    def endowment(self) -> Bundle:
        """Convenience accessor for current endowment."""
        return self.private_state.endowment

    @endowment.setter
    def endowment(self, value: Bundle) -> None:
        """Update the agent's endowment (e.g., after trade)."""
        self.private_state.endowment = value

    def utility(self) -> float:
        """Compute current utility level."""
        return self.private_state.utility()

    def utility_of(self, bundle: Bundle) -> float:
        """Compute utility of an arbitrary bundle."""
        return self.private_state.utility_of(bundle)

    def would_gain_from(self, new_bundle: Bundle) -> bool:
        """Check if trading to new_bundle would increase utility."""
        return self.utility_of(new_bundle) > self.utility()

    def __hash__(self) -> int:
        return hash(self.id)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Agent):
            return NotImplemented
        return self.id == other.id

    # =========================================================================
    # Belief System Methods
    # =========================================================================

    @property
    def has_beliefs(self) -> bool:
        """Check if belief system is enabled for this agent."""
        return self.memory is not None

    def enable_beliefs(
        self,
        update_rule: BeliefUpdateRule | None = None,
        memory_depth: int | None = 100,
    ) -> None:
        """
        Enable the belief system for this agent.

        Initializes memory, price belief, and type beliefs.
        If update_rule is not provided, uses BayesianUpdateRule.

        Args:
            update_rule: Rule for updating beliefs (default: BayesianUpdateRule)
            memory_depth: Maximum observations to store (None = unlimited)
        """
        from microecon.beliefs import (
            AgentMemory,
            PriceBelief,
            BayesianUpdateRule,
        )

        self.memory = AgentMemory(max_depth=memory_depth)
        self.price_belief = PriceBelief()
        self.type_beliefs = {}
        self.update_rule = update_rule if update_rule is not None else BayesianUpdateRule()

    def disable_beliefs(self) -> None:
        """Disable the belief system, clearing all memory and beliefs."""
        self.memory = None
        self.price_belief = None
        self.type_beliefs = None
        self.update_rule = None

    def get_believed_alpha(self, partner_id: str) -> float | None:
        """
        Get believed alpha for a partner, or None if no belief exists.

        Args:
            partner_id: ID of the partner agent

        Returns:
            Believed alpha if belief exists, else None
        """
        if self.type_beliefs is None:
            return None
        belief = self.type_beliefs.get(partner_id)
        return belief.believed_alpha if belief is not None else None


def create_agent(
    alpha: float,
    endowment_x: float,
    endowment_y: float,
    perception_radius: float = 3.0,
    discount_factor: float = 0.95,
    bargaining_power: float = 1.0,
    movement_budget: int = 1,
    agent_id: str | None = None,
) -> Agent:
    """
    Factory function to create an agent with Cobb-Douglas preferences.

    Args:
        alpha: Cobb-Douglas preference parameter in (0, 1)
        endowment_x: Initial holdings of good x
        endowment_y: Initial holdings of good y
        perception_radius: How far the agent can observe
        discount_factor: Time preference delta in (0, 1)
        bargaining_power: Intrinsic bargaining power w_i (default 1.0). Used by
            AsymmetricNashBargainingProtocol. Independent of discount_factor.
        movement_budget: Squares per tick
        agent_id: Optional explicit ID (for reproducibility). If None, uses UUID.

    Returns:
        A new Agent instance
    """
    preferences = CobbDouglas(alpha)
    endowment = Bundle(endowment_x, endowment_y)
    private_state = AgentPrivateState(preferences, endowment)

    agent = Agent(
        private_state=private_state,
        perception_radius=perception_radius,
        discount_factor=discount_factor,
        bargaining_power=bargaining_power,
        movement_budget=movement_budget,
    )

    # Override ID if explicit ID provided (for reproducibility)
    if agent_id is not None:
        agent.id = agent_id

    return agent
